FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /source

COPY ./DocumentXmlProcessorContext ./DocumentXmlProcessorContext/
COPY ./ProcessingCommon ./ProcessingCommon/
COPY ./DocumentXmlProcessorAPI ./DocumentXmlProcessorAPI/
COPY nuget.config ./nuget.config

RUN dotnet restore DocumentXmlProcessorAPI/DocumentXmlProcessorAPI.csproj \
    && dotnet restore DocumentXmlProcessorContext/DocumentXmlProcessorContext.csproj \
    && dotnet restore ProcessingCommon/ProcessingCommon.csproj

WORKDIR /source/DocumentXmlProcessorAPI
RUN dotnet publish -c Release -o /app --no-restore --configfile ../nuget.config


FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS runtime
WORKDIR /app
COPY --from=build /app ./
COPY ./DocumentXmlProcessorAPI/appsettings.json ./

ENTRYPOINT ["dotnet", "DocumentXmlProcessorAPI.dll"]
