FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /source

# Copy only necessary .csproj files for caching
COPY ./ProcessingCommon/ProcessingCommon.csproj ./ProcessingCommon/
COPY ./XsltProcessor/XsltProcessor.csproj ./XsltProcessor/




# Restore dependencies
RUN dotnet restore XsltProcessor/XsltProcessor.csproj

# Copy only necessary source code after restore
COPY ./ProcessingCommon ./ProcessingCommon/
COPY ./XsltProcessor ./XsltProcessor/

WORKDIR /source/XsltProcessor
RUN dotnet publish XsltProcessor.csproj -c $BUILD_CONFIGURATION -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS runtime
WORKDIR /app
COPY --from=build /app ./
COPY ./XsltProcessor/appsettings.json ./
ENTRYPOINT ["dotnet", "XsltProcessor.dll"]