using System;
using System.Collections.Generic;

namespace XsltTester.Entity;

public partial class GsObjectDocument
{
    public Guid DocumentId { get; set; }

    public Guid ParentId { get; set; }

    public string Type { get; set; } = null!;

    public string AlbumVersion { get; set; } = null!;

    public bool IsDeleted { get; set; }

    public DateTime DateBorn { get; set; }

    public Guid AuthorId { get; set; }

    public string? Comment { get; set; }

    public bool? IsValid { get; set; }

    public int OrderNumber { get; set; }

    public bool IsCorrection { get; set; }

    public bool IsPaper { get; set; }

    public Guid? OriginalId { get; set; }

    /// <summary>
    /// Указывает на то, что документ был открыт в &quot;полной&quot; версии редактора и в дальнейшем его можно открывать только в &quot;полной&quot; версии, чтобы не пострадали поля, не отображённые в обычный редактор
    /// </summary>
    public bool AutoGeneratedEditor { get; set; }

    public bool WasCreatedFromProfile { get; set; }

    public virtual AuthUserProfile Author { get; set; } = null!;

    public virtual GsDocumentAttr? GsDocumentAttr { get; set; }

    public virtual GsDocumentXml? GsDocumentXml { get; set; }

    public virtual GsPiDocument? GsPiDocument { get; set; }

    public virtual GsTdDocument? GsTdDocument { get; set; }

    public virtual ICollection<GsTemplate> GsTemplates { get; } = new List<GsTemplate>();
}
